- moment-timezone.js
- tests/moment-timezone/needs-offset.js
- tests/moment-timezone/parse.js
Currently, this is happening.
```js
var a = moment.tz([2014, 9, 1], 'Europe/London');
var b = moment.tz(a, 'Europe/London');
console.log(a.format()); // 2014-10-01T00:00:00+01:00
console.log(b.format()); // 2014-09-30T23:00:00+01:00
```
Instead, this should happen.
```js
var a = moment.tz([2014, 9, 1], 'Europe/London');
var b = moment.tz(a, 'Europe/London');
console.log(a.format()); // 2014-10-01T00:00:00+01:00
console.log(b.format()); // 2014-10-01T00:00:00+01:00
```
> Creating a moment with a timezone from another moment.

- moment-timezone.js
This adds an error message when loading moment-timezone twice. This addresses #212.
http://jsfiddle.net/eLh5m79c/
> Log an error if moment timezone was already loaded. #212

- moment-timezone.js
- tests/moment-timezone/parse.js
This addresses the bugs in #197.
When parsing with `moment()` instead of `moment.tz()` into a default timezone, the input was being parsed into local time and then the timezone was changed in place.
This accounts for parsing into local time and changes the offset accordingly to retain the correct time, offset, and timezone.
http://jsfiddle.net/jj0s0s1m/2/
```js
moment.tz.setDefault("America/Los_Angeles");
moment("2015-03-26");                           // 2015-03-26T00:00:00-07:00
moment("2015-03-26 00:00");                     // 2015-03-26T00:00:00-07:00
moment("09.04.2015 22:22", "DD.MM.YYYY HH:mm"); // 2015-04-09T22:22:00-07:00
moment.tz.setDefault("America/New_York");
moment("2015-03-26");                           // 2015-03-26T00:00:00-04:00
moment("2015-03-26 00:00"); …
```
> Fix parsing into a default zone.

- moment-timezone.js
- tests/moment-timezone/link.js
- tests/moment-timezone/names.js
Another alternative to #211 and #215.
This approach is much closer to the approach in #211, but cleans up a bunch of internals in the process.
We load data like below. This is the example at https://jsfiddle.net/rn58wmvn/3/.
```js
moment.tz.load({
version: "2015a",
zones: [ "America/Chicago|CST CDT|60 50|01010101010101010101010|1BQU0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Rd0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0"],
links: ["America/Chicago|US/Central"]
});
```
The internal representation looks like this.
```js
var links = {
america_chicago: 'us_central',
us_central: 'america_chicago'
};
var zones = {
america_chicago: 'America/Chicago|CST CDT|60 50|0101010101010101...'
};
var names = {
america_chicago: 'America/Chicago',
us_central: 'US/Central'
};
```
Now we try to load the …
> Restructure zone getter to allow for lazy unpacking.

- package.json
I using [JSPM] to manage my dependence.
[JSPM] using [SystemJS] for loading library.
BUT, in `index.js`
```
var moment = module.exports = require("./moment-timezone");
moment.tz.load(require('./data/packed/latest.json'));
```
[SystemJS] didn't support `require('./data/packed/latest.json')'` for load json.
My fix:
I add [JSPM] options in package.json, make [JSPM] using `builds/moment-timezone-with-data.js` instead of `index.js`
Then everything is works for me.
[JSPM]:https://github.com/jspm/jspm-cli
[SystemJS]:https://github.com/jspm/jspm-cli
> add main file mapping for jspm

- .npmignore
This makes it possible for people who use npm for browser-side package
management to use moment-timezone directly without having to build it.
> Fix #195: Include builds dir in npm package

- moment-timezone.js
- tests/moment-timezone/guess.js
This addresses the `1. Inspect Environment` part of https://github.com/moment/moment-timezone/pull/220#issuecomment-146251011.
It loops over each month in the 4 years surrounding the current date and builds an array of `OffsetAt` objects for each time the offset changed. Within a month, it uses a binary search to find the exact minute the offset changed.
The number of lookups is fairly consistent across timezones. There are a minimum of 48 lookups (1 per month), and for each month that has a change in offset, only ~16 more lookups are needed to find the exact time of change. This results in ~180 lookups for timezones with DST, and 315 for a more complicated zone like Morocco.
This does not address `2. Broad Search`, or `3. Narrow Search + Score`, but those can be addressed in `addZone` …
> Add user offset to help with guesses.

- moment-timezone-utils.js
- moment-timezone.js
Elements with IDs automatically have their IDs exposed. This causes errors where `module` is not defined, and yet `module.exports = moment-timezone` is run.
If possible, could you release this as a patch release?
> Fix issue when an element with ID of `exports` is defined in the browser.

- moment-timezone.js
This is the last step for guessing timezones.
The list of 600 zones is filtered down to the 20 or so that are applicable to the user's offsets. Then, when we get a list of zones to check against, we only have to check against that small handful.
I'd really like to get this feature out the door, so I'll be merging this in over the weekend, and plan to merge the `guess-timezone` branch into develop and release it next Tuesday. We can always improve the algorithm once it is released.
> Filter by known offsets before guessing timezone

- package.json
> You can write all package properties at the base of the package.json, or if you don't want to change existing properties that you'd like to use specifically for npm, you can write your jspm-specific configuration inside the jspm property of package.json, and jspm will use these options over the root level configuration options.
https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#prefixing-configuration
I think we can just drop the `jspm.dependencies` property and jspm will use the root `dependencies` configuration.
Addresses #280 and #269.
> Remove jspm deps so that the root package.json deps are used.

- moment-timezone.js
The timezone abbreviation(Taiwan or China) on "Chrome / Windows 7" isn't an alphabet string.
It returns something like this:
```
(new Date()).toTimeString()
=> '17:56:31 GMT+0800 (台北標準時間)'
```
I've changed the regular expression in `OffsetAt` to let `abbr` property from non-alphabet timezones   as `undefined`
> Ensure timezone abbreviations are in alphabets

- moment-timezone.js
- tests/moment-timezone/guess.js
> Handle uncommon output from Date#toTimeString.

- moment-timezone.js
Since the ECMA-402 Internationalization API provides a mechanism to get the current time zone, we should use it when available and fully implemented.
Note that we also need to guard against a few bad android implementations that return non-IANA time zone IDs.  (jstzdetect ran into this)
This will address #290
> Use Intl API for guessing when available

- moment-timezone.js
- tests/helpers/helpers.js
- tests/moment-timezone/guess.js
Continuing work on #291.
> Since the ECMA-402 Internationalization API provides a mechanism to get the current time zone, we should use it when available and fully implemented.
All of the dot accessors in `Intl.DateTimeFormat().resolvedOptions().timeZone` were worrying me, especially with a relatively new browser api, so I switched from the `typeof` and `isFunction` checks to a `try/catch`.
I also added a check that the output from `Intl.DateTimeFormat().resolvedOptions().timeZone` was actually loaded, logging an error if it wasn't.
> Continuing: use Intl API for guessing when available

- moment-timezone.js
- tests/moment-timezone/guess.js
I found that Intl.DateTimeFormat().resolvedOptions().timeZone returned undefined in FireFox 45.0.1. I'm not sure if my environment is weird or what. This pull request checks for that case and doesn't print out an error, since it doesn't make sense to report the error "Moment Timezone found undefined from the Intl api, but did not have that data loaded."
> Checking for undefined Intl.DateTimeFormat().resolvedOptions().timeZone

- tasks/data-dedupe.js
Due to changes in the tzdata, we can no longer grab the version number from the `Makefile`.  Until the tz list resolves this, the best we can do is take the first release mentioned from the `NEWS` file.
This is the same approach [being taken by other library maintainers](http://mm.icann.org/pipermail/tz/2016-October/024279.html).
> Fix version number for latest tzdata

- moment-timezone.js
Remove `console.log` of multiple moment instances. Temporary patch for issue #231 until final solution has been implemented.
> Remove Node Error Logging

- moment-timezone.js
- tests/helpers/helpers.js
- tests/moment-timezone/guess.js
- tests/moment-timezone/zone.js
>  zone.offset has been deprecated in favor of zone.utcOffset

- moment-timezone.js
- tests/moment-timezone/utc.js
> Convert to tz keeping wall time

- moment-timezone.js
Fixes #423 by ignoring any results from the Intl API that aren't at least three characters long.
> Ensure Intl response is valid

- changelog.md
- package.json
It avoids having 2 instances of moment loaded in the project.
Fixes https://github.com/moment/moment-timezone/issues/132
Fixes https://github.com/moment/moment-timezone/issues/449
> Move moment to peerDependencies

- moment-timezone.js
This PR stabilizes the sorting as it was instable before NodeJS 11 (V8 v7.0) and in NodeJS it was stabilized as the sorting algorithm was changed to TimSort with a pre-peocessing and a post-processing phase.
References:
https://github.com/nodejs/node/issues/24294
https://v8.dev/blog/array-sort
Probably we should change the added logic to order by name because `America/Caracas` and `America/Santo_Domingo` have the same `abbrScore`, `offsetScore` and `zone.population` but `C` comes before `S` in the alphabet and so it should be probably first (many breaking tests due to stable sorting now).
```
ZoneScore {
zone: {
name: 'America/Caracas',
abbrs: [Array],
untils: [Array],
offsets: [Array],
population: 2900000
},
offsetScore: 0,
abbrScore: 9
},
ZoneScore {
zone: {
name: …
```
> fix: stabilize Array.sort

- .travis.yml
- changelog.md
The latest 2 versions stated in the current changelog were shifted, resulting in misleading versions (0.5.29 doesn't exist yet).
> Fixed changelog to represent proper release versions

- Gruntfile.js
- tasks/builds.js
It's 2023 now, these files are producing incorrect results for the current year.
Fixes #1035
> Add deprecation warning to 2012-2022 pre-built files
